// <auto-generated />
namespace Kramer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CleaningUserResquests : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CleaningUserResquests));
        
        string IMigrationMetadata.Id
        {
            get { return "201702081714038_CleaningUserResquests"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
