// <auto-generated />
namespace Kramer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CorrecaoUserRequest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrecaoUserRequest));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151835267_CorrecaoUserRequest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
